name: audio_record
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  audioplayers: ^1.0.1
  cupertino_icons: ^1.0.2
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  get: ^4.6.5
  lottie: ^1.3.0
  path_provider: ^2.0.11
  record: ^4.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/lottie/
  uses-material-design: true

